### ISSUE TITLE
无法打包node模块

### ISSUE THREAD

**Issue by mobailabs** [leftstick/generator-electron-naive#1]
打包的时候,无法打包node模块。  
看到有个参数 rebuild，设置为true后，打包出错。
![image](https://cloud.githubusercontent.com/assets/1415418/15797729/4fbea95a-2a54-11e6-87f9-d571a5a72202.png)

**Comment by mobailabs** [comment]
查找后发现需要有apm，我安装了atom之后，可以支持执行，没有错误了。但是没有把native-module打包进去。

**Comment by leftstick** [comment]
参照[Using Native Node Modules](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md)这一章节，已经`re-build`成功了么？

然后修改`gulpfile.js`里的`dist`任务，里面有个`ignore`属性，现在默认是把`node_modules`目录全部过滤了。你改改试试

**Comment by mobailabs** [comment]
搞订.看了你的源码, `use electron-packager instead of gulp-electron since it's more nature`,但是 yo 官网还用的 gulp, 我一直用`electron-packager`就好着.谢谢!

**Comment by leftstick** [comment]
OK，我想我也是时候重构一下这个项目了，想办法把gulp引用去掉。谢谢反馈

**Comment by mobailabs** [comment]
支持这个项目。的确，gulp引入现在也没有必要了。
